---
key: cgmc_music_mix
model:
  type: CGMC
  hop: 1
  in_nfeats: 32
  out_nfeats: 32
  in_efeats: 32
  out_efeats: 32
  num_heads: 4
  edge_dropout: 0.5
  review: true
  rating: true
  timestamp: true
  node_features: onehot
  mpnn_type: mix

dataset:
  name: music
  file_name: music_core
  # efeat: music_sbert_review_whitening32.npy
  efeat: music_sbert_review_msmarco_whitening32.npy


train:
  device: 0
  epochs: 20
  batch_size: 128
  learning_rates:
    - 1e-3
    - 2e-3
    - 5e-4
  weight_decay: 0.0
  lr_decay_step: 5
  lr_decay_factor: 0.90
  log_interval: 100
  log_dir: log

